### ISSUE TITLE
Error on upgrading to Super-Heavy equipment

### ISSUE THREAD

**Issue by Turtlelord26** [bleehu/KWWarfareUnits#19]
![image](https://github.com/bleehu/KWWarfareUnits/assets/23040366/f03e5a7e-942b-4dd9-91b6-67cf4637a773)

Upgrading from Heavy to Super-Heavy produces this card image (null equipment) and dropdown selections (empty equipment dropdown), and softlocks any further attempts to upgrade or downgrade equipment until the card is regenerated (the upgrade and downgrade buttons do nothing - not even bring up the error prompt)

**Comment by bleehu** [comment]
Fixed in PR 23
