### ISSUE TITLE
Fails to launch after #4

### ISSUE THREAD

**Issue by Turtlelord26** [bleehu/KWWarfareUnits#5]
> D:\[...]\KWWarfareUnits>py kw_units_app.py
Traceback (most recent call last):
  File "D:\[...]\KWWarfareUnits\kw_units_app.py", line 8, in <module>
    from KingdomsAndWarfare.Traits.Traits import Trait
ModuleNotFoundError: No module named 'KingdomsAndWarfare.Traits'

**Comment by Turtlelord26** [comment]
Appears to be solved by changing kw_units_app.py line 8 to `from KingdomsAndWarfare.Trait.Trait import Trait`

**Comment by bleehu** [comment]
Willfix soon.

**Comment by Turtlelord26** [comment]
After recent code updates, issue persists due to absence of Traits directory in git.
